version: 2.1
jobs:
  build-and-test-java:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build clean package
          command: mvn --file java --batch-mode --define skipTests clean package
      - run:
          name: Run tests
          command: mvn --file java --batch-mode integration-test
  build-and-test-js:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test

workflows:
  build-and-test:
    jobs:
      - build-and-test-java
      - build-and-test-js
