version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -f java -B -D skipTests clean package
      - run:
          name: Test
          command: mvn -f java test
workflows:
  build-and-test:
    jobs:
      - build-and-test
